# Generated by Django 2.0.6 on 2018-09-15 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=64, verbose_name='銀行名')),
                ('principal', models.PositiveIntegerField(verbose_name='元本')),
                ('first_payment_date', models.DateField(verbose_name='初回返済日')),
                ('first_payment_amount', models.PositiveIntegerField(verbose_name='初回返済額')),
                ('second_payment_amount', models.PositiveIntegerField(verbose_name='二回目返済額')),
                ('count', models.PositiveIntegerField(verbose_name='返済回数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='返済日')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='返済額')),
                ('balance', models.PositiveIntegerField(verbose_name='残高')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bankuru.Debt')),
            ],
        ),
    ]
