# Generated by Django 2.0.6 on 2018-09-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankuru', '0002_auto_20180927_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
