# Generated by Django 2.0.6 on 2018-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankuru', '0003_debt_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='current_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='現在残高'),
        ),
    ]
