# Generated by Django 2.0.6 on 2018-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankuru', '0004_debt_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='last_payment_date',
            field=models.DateField(blank=True, auto_now=True, verbose_name='最終返済日'),
            preserve_default=False,
        ),
    ]
