# Generated by Django 2.0.6 on 2018-09-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankuru', '0005_debt_last_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='interest',
            field=models.FloatField(default=0, verbose_name='金利'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='last_payment_date',
            field=models.DateField(blank=True, verbose_name='最終返済日'),
        ),
    ]
