# Generated by Django 2.0.6 on 2018-09-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankuru', '0006_auto_20180928_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='current_balance',
        ),
    ]
