# Generated by Django 2.0.6 on 2018-09-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankuru', '0007_remove_debt_current_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='count',
            new_name='payment_terms',
        ),
    ]
