# Generated by Django 2.0.6 on 2018-10-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankuru', '0008_auto_20180929_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_dhosho',
            field=models.BooleanField(default=False, verbose_name='代表者保証あり'),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_kyokai',
            field=models.BooleanField(default=False, verbose_name='保証協会あり'),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_tanpo',
            field=models.BooleanField(default=False, verbose_name='担保あり'),
        ),
    ]
